apiVersion: v1
kind: Service
metadata:
  name: cdisched-svc
  labels:
    app: cdisched
spec:
  type: ClusterIP
  selector:
    app: cdisched
  ports:
  - name: cdisched-svc-port
    port: 8080
    protocol: TCP
    targetPort: 8080
