apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdisched
spec:
  selector:
    matchLabels:
      app: cdisched
  template:
    metadata:
      labels:
        app: cdisched
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      securityContext: {}
      automountServiceAccountToken: false
      dnsPolicy: ClusterFirst
      containers:
      - name: cdisched
        image: ${{ vars.JFROG_URL }}/${{ vars.JFROG_CONTAINER }}/cdisched:${{ vars.SHORT_NAME }}_${{ github.run_number }}
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 32m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        imagePullPolicy: Always
        terminationMessagePolicy: File
        env:
        - name: PORT
          value: "8080"
        envFrom:
        - configMapRef:
            name: env-configmap
        - secretRef:
            name: env-secrets
